### PR TITLE
Libnegf up

### PR DESCRIPTION
**Pull request by pecchia**
- Avoid allocation of the Sqr Hamiltonian when GF solver is used.
- Allow efficient memsaving algorithm for T(E)
- Align libNEGF to latest HEAD

### CODE REVIEW

**Comment by aradi** [comment]
As we have now the option to download the externals on-the-fly during the build, if you update a submodule, the corresponding new commit ID must be also adjusted in the build system. You can use  `utils/test/check_submodule_commits` for this. (This is actually the main reason, why the TravisCI fails).

Also, you have several commits which are not associated with your GitHub account, you should register your new email address at your GitHub account...

**Comment by aradi** [comment]
It seems, you have also updated scalapackfx and mpifx to current master. That must be reverted before merge, as those were already pinned to tagged releases of those libraries.

**Comment by aradi** [comment]
As the changes are trivial, I'd suggest to derive a new branch based on current master, updated libNEGF only and apply the change to initprogram.F90. You can then force push. You can force push the new branch into this PR if you wish, though.

**Comment by pecchia** [comment]
Hi,

 

The libnegf-up branch indeed has scalapackfx and mpifx that *do not mach*

what happens if I do:

 

utils/test/check_submodule_commits –u ?

 

in which direction does this updates ?

 

Alex

 

Da: Bálint Aradi [mailto:notifications@github.com] 
Inviato: mercoledì 11 novembre 2020 12:52
A: dftbplus/dftbplus
Cc: Alessandro Pecchia; Author
Oggetto: Re: [dftbplus/dftbplus] Libnegf up (#669)

 

As we have now the option to download the externals on-the-fly during the build, if you update a submodule, the corresponding new commit ID must be also adjusted in the build system. You can use utils/test/check_submodule_commits for this. (This is actually the main reason, why the TravisCI fails).

Also, you have several commits which are not associated with your GitHub account, you should register your new email address at your GitHub account...

**Comment by pecchia** [comment]
Hi again,

 

sorry, I think I understood. I guess you want to have tag 1.0 of mpifx and 1.0.1 for scalapackfx.

 

Is there a simple way to revert my references to the correct ones ?

 

Alex

 

 

 

Da: Bálint Aradi [mailto:notifications@github.com] 
Inviato: mercoledì 11 novembre 2020 12:52
A: dftbplus/dftbplus
Cc: Alessandro Pecchia; Author
Oggetto: Re: [dftbplus/dftbplus] Libnegf up (#669)

 

As we have now the option to download the externals on-the-fly during the build, if you update a submodule, the corresponding new commit ID must be also adjusted in the build system. You can use utils/test/check_submodule_commits for this. (This is actually the main reason, why the TravisCI fails).

Also, you have several commits which are not associated with your GitHub account, you should register your new email address at your GitHub account...

**Comment by aradi** [comment]
This would be the correct way of doing so:
```
git co master
git pull --ff-only upstream master
git co libnegf-up
git co upstream/master -- external/scalapackfx/origin external/mpifx/origin
git ci -m 'Downgrade scalapackfx and mpifx to version on main'
git submodule update --recursive
```

**Comment by pecchia** [comment]
I think I fixed the correct references now. Also here many commits can be squashed in one

**Comment by aradi** [comment]
I'll merge it. Could you please tag the actual commit of libNegf with a semantic version tag (e.g. `0.4`)?

**Pull request merged**
