### PR TITLE
Update script path for sh headers

### PR DESCRIPTION
**Pull request by bhourahine**
Follow-up to #1290

### CODE REVIEW

**Review by vanderhe — COMMENTED** [review]
Is it a problem that e.g. in the testrun.sh files the shebang is below the copyright-header after executing `set_source_headers`? Might be a stupid question, just wondered...

**Comment by bhourahine** [comment]
> Is it a problem that e.g. in the testrun.sh files the shebang is below the copyright-header after executing `set_source_headers`? Might be a stupid question, just wondered...

That will run as a script with whatever the default shell is as interpreter, so real comments should definitely be after the shebang.

**Comment by vanderhe** [comment]
> > Is it a problem that e.g. in the testrun.sh files the shebang is below the copyright-header after executing `set_source_headers`? Might be a stupid question, just wondered...
> 
> That will run as a script with whatever the default shell is as interpreter, so real comments should definitely be after the shebang.

I see. What about the command line wrappers in `dptools/bin`, there the shebang is above the copyright header, even after executing the script and therefore not consistent with the `testrun.sh` files. Do we care about that?

**Comment by bhourahine** [comment]
The shebang should always be at the top. I didn't write this script so haven't worked out why it is chewing these up. To be honest, this looks over engineered and fragile (a suitable regex replacement on the DFTB+ copyright string with a range of quote marks in the match, plus the unix find, would work and not need the list of paths to be maintained).

**Comment by vanderhe** [comment]
> The shebang should always be at the top. I didn't write this script so haven't worked out why it is chewing these up. To be honest, this looks over engineered and fragile (a suitable regex replacement on the DFTB+ copyright string with a range of quote marks in the match, plus the unix find, would work and not need the list of paths to be maintained).

@bhourahine See my suggestion of [#13](https://github.com/bhourahine/dftbplus/pull/13).

**Comment by bhourahine** [comment]
@vanderhe shall we just merge this?

**Pull request merged**
