### PR TITLE
Minor typo in readme

### PR DESCRIPTION
**Pull request by bhourahine**

### CODE REVIEW

**Review by awvwgk — COMMENTED** [review]
Is this targeting the right branch / repository?

**Comment by bhourahine** [comment]
@awvwgk it's for a typo introduced in the release-22.1 branch but absent from main. Presumably once 22.1 is merged/cherry-picked it becomes main relevant.

**Comment by awvwgk** [comment]
We will fast-forward *main* to the *release* branch afterwards and include the patch this way.

**Comment by awvwgk** [comment]
I guess this can be closed now?

**Comment by bhourahine** [comment]
> I guess this can be closed now?

Changes (such as they are) now rebased on main.

**Review by awvwgk — APPROVED** [review]

**Pull request merged**
