### PR TITLE
Disable pythonapi tests without python

### PR DESCRIPTION
**Pull request by steinmig**
Allows to only have the C API without the Python API and still have all unittests passing

### CODE REVIEW

**Review by awvwgk — APPROVED** [review]
Thanks for sharing. Looks good to me.

**Comment by steinmig** [comment]
No clue why this random function is not in the coverage anymore :man_shrugging: 
Is the CI without Python?

**Comment by awvwgk** [comment]
Yes, the Python API is currently not tested in CI.

**Comment by bhourahine** [comment]
More than than ( #834 )

**Pull request merged**
