### PR TITLE
Revise installation of Python components

### LINKED ISSUE #1264: Instalation of Python bindings failed
**Describe the bug**

I was able to compile dftb+ with `cmake -DBUILD_SHARED_LIBS=Y -DWITH_API=Y -DWITH_PYTHON=Y ..` as decribed [here](https://dftbplus-recipes.readthedocs.io/en/latest/interfaces/pyapi/pyapi.html) and [here](https://github.com/dftbplus/dftbplus/blob/main/INSTALL.rst) but it failed on `make install`

**To Reproduce**

* `cmake .. -DWITH_TBLITE=N -DWITH_SOCKETS=Y -DWITH_GPU=N -DBUILD_SHARED_LIBS=Y -DWITH_API=Y -DWITH_PYTHON=Y -DCMAKE_INSTALL_PREFIX=$HOME/SW/dftbplus`

* `make install` returns
```
...
-- Up-to-date: /home/prokop/SW/dftbplus/bin/skderivs
-- Up-to-date: /home/prokop/SW/dftbplus/bin/integvalue
-- Up-to-date: /home/prokop/SW/dftbplus/bin/polyvalue
-- Up-to-date: /home/prokop/SW/dftbplus/bin/splvalue
-- Up-to-date: /home/prokop/SW/dftbplus/bin/printunits
-- Up-to-date: /home/prokop/SW/dftbplus/bin/modes
-- Up-to-date: /home/prokop/SW/dftbplus/bin/waveplot
/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/util.py", line 212, in subst_vars
    return _subst_compat(s).format_map(lookup)
KeyError: 'DESTDIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prokop/git_SW/dftbplus/tools/dptools/setup.py", line 4, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py", line 45, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py", line 439, in finalize_options
    self.expand_basedirs()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py", line 619, in expand_basedirs
    self._expand_attrs(['install_base', 'install_platbase', 'root'])
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py", line 613, in _expand_attrs
    val = subst_vars(val, self.config_vars)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/util.py", line 214, in subst_vars
    raise ValueError(f"invalid variable {var}")
ValueError: invalid variable 'DESTDIR'
-- Up-to-date: /home/prokop/SW/dftbplus/bin/calc_timeprop_maxpoldir
-- Up-to-date: /home/prokop/SW/dftbplus/bin/calc_timeprop_spectrum
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-targets.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-targets-relwithdebinfo.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-config.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-config-version.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomBlas.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/Findelsi.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/CustomLibraryFinder.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomPlumed.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomMagma.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomScalapack.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomLapack.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomArpack.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/pkgconfig/dftbplus.pc
...
```

**Additional context**

Tested on Ubuntu 22 LTS

### PR DESCRIPTION
**Pull request by vanderhe**
Possibly fixes #1264.

Remark: This PR is restricted to the installation mechanism itself, the already outdated documentation (e.g. README files) further needs to be revamped a.s.a.p.

### CODE REVIEW

**Comment by ProkopHapala** [comment]
> Possibly fixes #1264.
> 
> Remark: This PR is restricted to the installation mechanism itself, the already outdated documentation (e.g. README files) further needs to be revamped a.s.a.p.

@vanderhe Can I somehow pull/clone this update before it is merged ?

**Comment by vanderhe** [comment]
> > Possibly fixes #1264.
> > Remark: This PR is restricted to the installation mechanism itself, the already outdated documentation (e.g. README files) further needs to be revamped a.s.a.p.
> 
> @vanderhe Can I somehow pull/clone this update before it is merged ?

@ProkopHapala Sure, that would be very much appreciated. The simplest way might just be
```
git clone https://github.com/vanderhe/dftbplus.git dftbplus-vanderhe
cd dftbplus-vanderhe/
git checkout fixPythonInstallation
```

**Comment by vanderhe** [comment]
> no I have different error
> 
> cmake:
> 
> ```
> prokop@DesktopGTX3060:~/git_SW/dftbplus-vanderhe/Build$ cmake .. -DWITH_TBLITE=N -DWITH_SOCKETS=Y -DWITH_GPU=N -DBUILD_SHARED_LIBS=Y -DWITH_API=Y -DWITH_PYTHON=Y -DCMAKE_INSTALL_PREFIX=$HOME/SW/dftbplus
> -- Reading global build config file: /home/prokop/git_SW/dftbplus-vanderhe/config.cmake
> -- The Fortran compiler identification is GNU 11.3.0
> -- The C compiler identification is GNU 11.3.0
> -- Detecting Fortran compiler ABI info
> -- Detecting Fortran compiler ABI info - done
> -- Check for working Fortran compiler: /usr/bin/f95 - skipped
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Build type: RelWithDebInfo (default single-config)
> -- Reading build environment specific toolchain file: /home/prokop/git_SW/dftbplus-vanderhe/sys/gnu.cmake
> -- Flags for Fortran-compiler (build type: RelWithDebInfo):    -g -O2 -funroll-all-loops
> -- Flags for C-compiler (build type: RelWithDebInfo):    
> -- Found OpenMP_C: -fopenmp (found version "4.5") 
> -- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
> -- Found OpenMP: TRUE (found version "4.5")  
> -- Found Git: /usr/bin/git (found version "2.34.1") 
> -- Looking for Fortran sgemm
> -- Looking for Fortran sgemm - not found
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
> -- Found Threads: TRUE  
> -- Looking for Fortran sgemm
> -- Looking for Fortran sgemm - found
> -- Found BLAS: /usr/lib/x86_64-linux-gnu/libmkl_gf_lp64.so;/usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so;/usr/lib/x86_64-linux-gnu/libmkl_core.so;/usr/lib/gcc/x86_64-linux-gnu/11/libgomp.so;-lm;-ldl  
> -- Found CustomBlas: /usr/lib/x86_64-linux-gnu/libmkl_gf_lp64.so;/usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so;/usr/lib/x86_64-linux-gnu/libmkl_core.so;/usr/lib/gcc/x86_64-linux-gnu/11/libgomp.so;-lm;-ldl  
> -- Looking for Fortran cheev
> -- Looking for Fortran cheev - found
> -- Found LAPACK: /usr/lib/x86_64-linux-gnu/libmkl_gf_lp64.so;/usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so;/usr/lib/x86_64-linux-gnu/libmkl_core.so;/usr/lib/gcc/x86_64-linux-gnu/11/libgomp.so;-lm;-ldl;-lm;-ldl  
> -- Found CustomLapack: /usr/lib/x86_64-linux-gnu/libmkl_gf_lp64.so;/usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so;/usr/lib/x86_64-linux-gnu/libmkl_core.so;/usr/lib/gcc/x86_64-linux-gnu/11/libgomp.so;-lm;-ldl;-lm;-ldl  
> -- DFTB+ API version: 0.4.0
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/prokop/git_SW/dftbplus-vanderhe/Build
> ```
> 
> Compile and install:
> 
> ```
> prokop@DesktopGTX3060:~/git_SW/dftbplus-vanderhe/Build$ make -j10
> ...
> prokop@DesktopGTX3060:~/git_SW/dftbplus-vanderhe/Build$ make install
> ...
> -- Up-to-date: /home/prokop/SW/dftbplus/bin/modes
> -- Up-to-date: /home/prokop/SW/dftbplus/bin/waveplot
> Processing /home/prokop/git_SW/dftbplus-vanderhe/tools/dptools
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'done'
>   Getting requirements to build wheel: started
>   Getting requirements to build wheel: finished with status 'done'
>   Preparing metadata (pyproject.toml): started
>   Preparing metadata (pyproject.toml): finished with status 'done'
> Building wheels for collected packages: dptools
>   Building wheel for dptools (pyproject.toml): started
>   Building wheel for dptools (pyproject.toml): finished with status 'error'
>   error: subprocess-exited-with-error
>   
>   × Building wheel for dptools (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [2 lines of output]
>       warning: no files found matching 'README'
>       error: [Errno 2] No such file or directory: 'bin/dp_bands'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for dptools
> Failed to build dptools
> ERROR: Could not build wheels for dptools, which is required to install pyproject.toml-based projects
> -- Up-to-date: /home/prokop/SW/dftbplus/bin/calc_timeprop_maxpoldir
> -- Up-to-date: /home/prokop/SW/dftbplus/bin/calc_timeprop_spectrum
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-targets.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-targets-relwithdebinfo.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-config.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-config-version.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomBlas.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/Findelsi.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/CustomLibraryFinder.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomPlumed.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomMagma.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomScalapack.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomLapack.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomArpack.cmake
> -- Up-to-date: /home/prokop/SW/dftbplus/lib/pkgconfig/dftbplus.pc
> ```

@ProkopHapala Sorry, I think I have unwillingly re-introduced the bug while rebasing on the latest changes in main. Could you give it another try with the version I just force-pushed into this branch?

**Comment by vanderhe** [comment]
@ProkopHapala I have to admit I don't have an immediate step-by-step solution, but intend to further investigate. What seems so work for me is to just create a new virtual Python environment using `venv` and install the pythonapi via the usual `pip install tools/pythonapi/` mechanism. If that works for you too, feel free to stick with it as long as I can not come up with another solution. Also, the recipes are slightly outdated, sorry for the inconvenience, we have to catch up.

**Comment by vanderhe** [comment]
@ProkopHapala What may also work is to just set the PYTHONPATH manually, e.g. like so:
`export PYTHONPATH="${PYTHONPATH}:/path/to/dftbplus/install/folder/lib/python3.10/site-packages/`

**Comment by ProkopHapala** [comment]
> @ProkopHapala What may also work is to just set the PYTHONPATH manually, e.g. like so: `export PYTHONPATH="${PYTHONPATH}:/path/to/dftbplus/install/folder/lib/python3.10/site-packages/`

Hmm, the problem is probably that I don't have any folder like `dftbplus//lib/python3.10/site-packages/`. In my install folred `/home/prokop/SW/dftbplus/lib/` I have only this: `cmake  libdftbplus.so  pkgconfig`

Did I forget something when configuring cmake, or in some other step of the compilation/instllation?

`cmake .. -DWITH_TBLITE=N -DWITH_SOCKETS=Y -DWITH_GPU=N -DBUILD_SHARED_LIBS=Y -DWITH_API=Y -DWITH_PYTHON=Y -DCMAKE_INSTALL_PREFIX=$HOME/SW/dftbplus`

**Comment by vanderhe** [comment]
> > @ProkopHapala What may also work is to just set the PYTHONPATH manually, e.g. like so: `export PYTHONPATH="${PYTHONPATH}:/path/to/dftbplus/install/folder/lib/python3.10/site-packages/`
> 
> Hmm, the problem is probably that I don't have any folder like `dftbplus//lib/python3.10/site-packages/`. In my install folred `/home/prokop/SW/dftbplus/lib/` I have only this: `cmake libdftbplus.so pkgconfig`
> 
> Did I forget something when configuring cmake, or in some other step of the compilation/instllation?
> 
> `cmake .. -DWITH_TBLITE=N -DWITH_SOCKETS=Y -DWITH_GPU=N -DBUILD_SHARED_LIBS=Y -DWITH_API=Y -DWITH_PYTHON=Y -DCMAKE_INSTALL_PREFIX=$HOME/SW/dftbplus`

@ProkopHapala When testing this PR, I've used the following flags (`ENABLE_DYNAMIC_LOADING` required for the Python API):
`-DENABLE_DYNAMIC_LOADING=1 -DBUILD_SHARED_LIBS=1 -DWITH_API=1 -DWITH_PYTHON=1`

Am I right to assume that you have checked out the branch of this particular PR, as described above?

**Comment by vanderhe** [comment]
@bhourahine Shall we proceed/merge this?

**Comment by vanderhe** [comment]
@bhourahine Anything left to do here?

**Review by aradi — APPROVED** [review]

**Pull request merged**
