### PR TITLE
New geometry optimizer

### PR DESCRIPTION
**Pull request by awvwgk**
Very rough draft for implementing a new geometry optimizer, currently only LBFGS and RF without linesearch.

### Input

```cson
Driver = GeometryOptimization {
  Optimzer = Rational {}
  LatticeOpt = Yes
}
```

### Comparison of lattice optimization

| method | system | `ConjugateGradient` | `Optimizer::RF` | `Optimizer::FIRE` |
| --- | --- | --- | --- | --- |
| DFTB(mio)-D4 | acetic acid | did not converge | 156 steps | 162 steps |
| DFTB(mio)-D4 | adamantan | 386 steps | 117 steps | 277 steps |
| DFTB(mio)-D4 | ammonia | 592 steps | 71 steps | 91 steps |
| DFTB(mio)-D4 | anthracene | did not converge | 379 steps | did not converge |
| DFTB(mio)-D4 | benzene | 937 steps | 117 steps | did not converge |
| DFTB(mio)-D4 | CO2 | 152 steps | 61 steps | 912 steps |
| DFTB(mio)-D4 | cyanamide | did not converge | 197 steps | did not converge |
| DFTB(mio)-D4 | cytosine | did not converge | 241 steps | did not converge |
| DFTB(mio)-D4 | ethyl carbamate | did not converge | 181 steps | 347 steps |
| DFTB(mio)-D4 | formamide | did not converge | 190 steps | 207 steps |
| DFTB(mio)-D4 | hexamine | 281 steps | 37 steps | 94 steps |
| DFTB(mio)-D4 | hexdione | did not converge | 116 steps | 527 steps |
| DFTB(mio)-D4 | imidazole | did not converge | 256 steps | did not converge |
| DFTB(mio)-D4 | naphtalene | did not converge | 163 steps | 997 steps |
| DFTB(mio)-D4 | α oxalic acid | did not converge | 107 steps | 662 steps |
| DFTB(mio)-D4 | β oxalic acid | did not converge | 128 steps | 927 steps |
| DFTB(mio)-D4 | pyrazine | 609 steps | 88 steps | 284 steps |
| DFTB(mio)-D4 | pyrazole | did not converge | 329 steps | did not converge |
| DFTB(mio)-D4 | succinic | did not converge | 156 steps | 347 steps |
| DFTB(mio)-D4 | triazine | 883 steps | 107 steps | did not converge |
| DFTB(mio)-D4 | trioxane | 762 steps | 130 steps | 157 steps |
| DFTB(mio)-D4 | uracil | did not converge | 128 steps | 909 steps |
| DFTB(mio)-D4 | urea | 542 steps | 73 steps | 223 steps |
| GFN1-xTB | ice Ih | 789 steps | 184 steps | |
| GFN1-xTB | ice VI | did not converge | 173 steps | |
| GFN1-xTB | ice VII | 252 steps | 92 steps | |
| GFN1-xTB | ice VIII | 245 steps | 76 steps | |
| GFN1-xTB | ice XII | did not converge | 361 steps | |
| GFN1-xTB | ice XIV | did not converge | 326 steps | |
| GFN1-xTB | ice XV | did not converge | 157 steps | |

### Molecular optimization

| method | system | `CG`* | `LBFGS` | `FIRE` | `GDIIS` | `SD`* | `Opt::RF` | `Opt::LBFGS` | `Opt::FIRE` |
| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| GFN1-xTB | mindless 1 | 482 | 371 | 270 | failed | failed | 210 | 208 | 270 |
| GFN1-xTB | mindless 2 | 314 | 203 | 145 | 357 | failed | 146 | 140 | 145 |
| GFN1-xTB | mindless 3 | 583 | 466 | 353 | 884 | failed | 229 | 256 | 353 |
| GFN1-xTB | mindless 4 | 620 | 532 | 415 | 855 | failed | 280 | 317 | 415 |
| GFN1-xTB | mindless 5 | failed | 273 | 250 | failed | failed | 174 | 165 | 250 |

* CG: ConjugateGradient, SD: SteepestDescent

### TODO List

- [x] decide on bug-compatibility with previous implementation
- [x] cleanup, fix coding style
- [ ] testing
- [x] documentation
- [x] changelog

### CODE REVIEW

**Comment by aradi** [comment]
OK, I my suggestions with regarding of the structuring can be found in awvwgk/dftbplus#238. What still remains is:
* Document the parameters of the Fire optimizer in the manual
* Give at least one self-containing example in the manual with the new geometry driver.

**Comment by aradi** [comment]
Furthermore, I'd like to initiate a discussion on the input. I am not sure, if we should map 1-1 the internal structure to the input (although it makes things easy for us, it may mean a lot of extra typing for the users). From the user point of view, the input
```
Driver = GeometryOptimization {
  Optimizer = Rational {}
  Filter = Cartiesian {
    MovedAtoms = H
  }
  MaxSteps = 100
  OutputPrefix = "geom.out"
}
```
could be formulate much more compact as
```
Driver = GeometryOptimization {
  Optimizer = Rational {}
  MovedAtoms = H
  MaxSteps = 100
  OutputPrefix = "geom.out"
}
```
Do we have to expose the user to the `Filter` object (or is it just an internal detail, how we apply the various constaints...)

On the other hand, maybe we could use the opportunity to make the lattice optimization settings more extensible?
```
Driver = GeometryOptimization {
  Optimizer = Rational {}
  MovedAtoms = H
  LatticeOptimization {
     FixAngles = Yes/No
     FixLengths = Yes/No
     Isotropic = Yes/No
  }
  MaxSteps = 100
  OutputPrefix = "geom.out"
}
```
(or something else, which also allows for boundary condition optimization for the helical, if we ever make it work?)

**Comment by bhourahine** [comment]
> could be formulate much more compact as

Succinct input is definitely preferable. You probably want to retain the Cartesian though (as a logical flag?). Just in case Z-matrix or whatever is where Sebastian is going with this.

The FixAngles / whatever syntax should be designed to naturally evolve into fixing a sub-set of these

Lattice optimisation was working for helical back in the day, and at least the translational part should directly map onto these structures.

**Comment by awvwgk** [comment]
> Will we realistically have any case with `Filter = SomethingNonCartesian {...}`?

Having more than just Cartesian coordinates was kind of the plan for the geometry optimizer rewrite, however this PR only contains the Cartesian part to keep things simple for the initial review.

We can flatten the `Filter%Cartesian` logic and use something like:

```cson
Driver = GeometryOptimization {
  Optimizer = Rational {}
  MovedAtoms = 1:-1
  Lattice {}
}
```

I agree that the lattice optimization will potentially become more involved, maybe using a group that can be present instead of a boolean is more future-proof in the design.

**Review by bhourahine — APPROVED** [review]
LGTM
Couple of things for possible future PRs:
1. Lots of src/dftbp/geoopt/lbfgs2.F90 seems to not have any coverage, so probably needs a test case
2. The Davidson solver might be worth separating for other uses (Casida as a alternative to ARPACK for bottom state) or other drop in alternatives for solving the RF (ELSI_RCI)

**Pull request merged**
