### PR TITLE
Draft: Real time bond currents

### PR DESCRIPTION
**Pull request by fbonafe**
Implementation of bond currents following equation B3 in 10.1103/PhysRevB.94.075118

- [ ] check spin-polarized case and correct factor
- [ ] print "onsite atomic" currents
- [ ] documentation
- [ ] test: diatomic and infinite cable
- [ ] API routine

### CODE REVIEW

**Comment by aradi** [comment]
I converted this PR to draft in order to exclude from the list, if one filters the PRs with `-is:draft`... (If it is not a draft any more, feel free to convert it back to active, but then change also its title please :wink: )

**Comment by bhourahine** [comment]
@fbonafe do you want to keep this live?

**Comment by fbonafe** [comment]
@bhourahine @baradi09 we have another branch that if merged will supersede this PR. If it's more convenient for you, close it, I'll keep the to do list somewhere else for the new branch.

**Comment by bhourahine** [comment]
> @bhourahine @baradi09 we have another branch that if merged will supersede this PR. If it's more convenient for you, close it, I'll keep the to do list somewhere else for the new branch.

@fbonafe What happened about the other branch?

**Pull request closed without merging**
