### PR TITLE
Fix results.tag output

### PR DESCRIPTION
**Pull request by aradi**
Orbital populations are written for both spins, gross charge is calculated correctly for spin polarized case, spin polarizations are also written.

### CODE REVIEW

**Comment by bhourahine** [comment]
We really need to regression test the contents of this file (could to this as a hack with a shell script in the test system to re-names to autotest.tag for some specific example).

**Comment by awvwgk** [comment]
The tester could just enable such check in case a `_results.tag` file is found.

**Comment by aradi** [comment]
Sure, we can "hack" this in into (the already quite horrible) autotest-er script. :wink: Still, let's merge this first, if you agree and make that as a separate PR.

**Review by awvwgk — APPROVED** [review]

**Comment by bhourahine** [comment]
#731

**Pull request merged**
