### PR TITLE
Complex Anderson/DIIS mixer

### PR DESCRIPTION
**Pull request by vanderhe**
Completes the list of available mixers by implementing a complex-valued Anderson/DIIS pendant.

Follow-up to #1389.

To be merged _after_ #1389 and #1392 (needs to be rebased).

### CODE REVIEW

**Comment by bhourahine** [comment]
@vanderhe I'll wait for the merges and rebase before looking at this.

**Comment by vanderhe** [comment]
> @vanderhe I'll wait for the merges and rebase before looking at this.

Sure, thanks for going through the other PRs.

**Comment by vanderhe** [comment]
@bhourahine Rebased on #1392 and ready for review (this PR is of lower priority though).

**Review by bhourahine — APPROVED** [review]
LGTM. Please rebase, on main just in case.

**Comment by vanderhe** [comment]
@bhourahine Rebased on main.

**Pull request merged**
