### PR TITLE
Module names2

### PR DESCRIPTION
**Pull request by helmutwecke**
I changed the module names on all the necesary files. Now I am going to make the buildbot tests to assure everything is fine. @aradi

### CODE REVIEW

**Comment by helmutwecke** [comment]
@aradi I have merged master and solved the conflicts.

**Comment by helmutwecke** [comment]
@aradi All the Buildbot tests have passed successfully. This branch is ready to be merged into master

**Review by awvwgk — CHANGES_REQUESTED** [review]
This is a rather big change, touching all files and will probably conflict with all existing pull requests. I think it is a step in the right direction, still I have one suggestion.

Since this is now touching all the files (again), why don't we take the chance and sort the use statements in the same run? This could avoid a third big change to resort all imports in the course of the current refactoring.

**Comment by aradi** [comment]
@awvwgk Now, the modules are sorted. It indeed becomes considerably more readable, thanks for the idea. :wink:

**Review by awvwgk — APPROVED** [review]
Thanks for going the extra mile here. Much appreciated.

**Comment by bhourahine** [comment]
@aradi any reason not to now merge?

**Comment by aradi** [comment]
My plan was to merge #792 and #781 first (as they are basically ready to be merged), then update this branch and then merge it. (This should all happen today). Then, I'd immediately make the PR for the file-reshuffling, so that also that can be merged tomorrow or latest after a discussion on Wednesday.

**Review by awvwgk — COMMENTED** [review]
This PR changes some of the git submodules, but it is not supposed to.

**Comment by aradi** [comment]
@awvwgk Thanks, well spotted, I've corrected it. I am making last checks and tests now...

**Pull request merged**
