### PR TITLE
Fix block hermitian code and clean up

### PR DESCRIPTION
**Pull request by bhourahine**
* Moves the dense matrix symmetrization routines to a distinct module
* Cleans out un-used routines and redundant routines
* Rationalises routine names to make it clear that a triangle is copied
* Adds unit tests for serial case
* Adds BLACS matrix cases

### CODE REVIEW

**Comment by bhourahine** [comment]
Temporarily switch to draft, as want to add unit tests and simplify one routine name.

**Review by aradi — COMMENTED** [review]
I like the idea a lot to clean up the ambiguous naming we have. I have two comments on naming:

- We so far tried to use module names, which each member in the module path is not longer than 15 chars. `matrixoperations` is just one character too long. (What about `matrixops` instead?)
- It is not really a triangle copy in the comlex case. What about calling the interface `adjungateLowerTriangle()` or `transjugateLowerTriangle()`, which would also document, which triangle is the source, and would be valid for both, real and complex cases.

**Comment by bhourahine** [comment]
>     * It is not really a triangle copy in the comlex case. What about calling the interface `adjungateLowerTriangle()` or `transjugateLowerTriangle()`, which would also document, which triangle is the source, and would be valid for both, real and complex cases.
https://en.wikipedia.org/wiki/Adjugate_matrix implies that isn't the right terminology, but transjugate makes sense.
How about adjointLowerTriangle() ? This is slightly shorter.

**Comment by bhourahine** [comment]
@aradi Depending on what you think, I can squash the last 2 commits in. The first renames the module as suggested, the second changes the routine name using adjoint.

**Review by aradi — APPROVED** [review]

**Comment by fbonafe** [comment]
@bhourahine it seems the adjointLowerTriangle_BLACS that you added is not tested or used anywhere else in the code, can you give me an example of how to call it? It seems now we need it, maybe it's not necessary to have a wrapper but we definitely need to know how to call it.

**Pull request merged**
