### PR TITLE
Dense MPI-parallel HFX algos meta-programming

### PR DESCRIPTION
**Pull request by vanderhe**
Follow-up PR, supplementing #1553 by the respective MPI-parallel analogs.

While the meta-routine does add the complex case `addCamHamiltonianMatrix_cmplx_blacs()`, it does not unnecessarily inflate the code. The dangling routine will be useful as soon as #1390 has been merged.

To be merged _after_ #1553.

### CODE REVIEW

**Comment by vanderhe** [comment]
@bhourahine Rebased on #1553 and same feedback applied here.

**Comment by bhourahine** [comment]
@vanderhe can you rebase and squash now that #1553 is merged. Thx

**Comment by vanderhe** [comment]
> @vanderhe can you rebase and squash now that #1553 is merged. Thx

@bhourahine Sure, done.

**Review by bhourahine — APPROVED** [review]
LGTM

**Pull request merged**
