### PR TITLE
Simplify logic and reuse calls

### PR DESCRIPTION
**Pull request by bhourahine**

### CODE REVIEW

**Comment by vanderhe** [comment]
@bhourahine I did not yet have the time to figure out why the Intel workflow breaks, but #1419 now exhibits the same behavior.

**Comment by bhourahine** [comment]
@vanderhe Intel had a new release recently, possibly not unrelated...

**Comment by vanderhe** [comment]
@bhourahine Do we merge PRs, even though Intel fails (e.g. #1419)?

**Comment by bhourahine** [comment]
@vanderhe I've seen Intel fail after just changing comments in code, so probably a compiler bug. Hence, I think we discuss tomorrow, but don't think it should hold up merging branches that pass CI on everything else.

**Pull request merged**
