### PR TITLE
Modes eigenvector output bugfix

### PR DESCRIPTION
**Pull request by vanderhe**
At the moment the fields `eigenmodes` and `eigenmodes_scaled` in _vibrations.tag_ are always identical.

No need to recompute regression test, as there are none that cover this functionality. I will create another PR that decouples the calculation (and writing) of eigenvectors from animating selected modes. This PR will then further contain regression tests, at least that would be my suggestion.

To be merged after #1311.

### CODE REVIEW

**Comment by vanderhe** [comment]
@bhourahine The bug fix is now living in this PR.

**Review by bhourahine — COMMENTED** [review]
Please update on main (suspect you'll get conflicts on comment changes from #1311 )

**Comment by vanderhe** [comment]
> Please update on main (suspect you'll get conflicts on comment changes from #1311 )

@bhourahine Done, ready for review.

**Review by bhourahine — APPROVED** [review]
Looks fine as is. But is it worth adding a test case to get the coverage up for this? This might need a little work, as the eigenvector phases aren't portable between lapack implementations, so probably should be a separate PR.

**Comment by vanderhe** [comment]
> Looks fine as is. But is it worth adding a test case to get the coverage up for this? This might need a little work, as the eigenvector phases aren't portable between lapack implementations, so probably should be a separate PR.

I'm already working on it (in a separate branch that also decouples eigenvector printing from mode animation), thanks for the phase-reminder, I think I would have forgotten to deal with this issue.

**Pull request merged**
