### PR TITLE
Atq trans charges

### PR DESCRIPTION
**Pull request by thomas-niehaus**
Reintroduced ATQ.DAT which writes the transition charges for a given excited state. Now available also for non-hybrid and spin-polarized calculations. A test job has been added and the documentation modified.

### CODE REVIEW

**Comment by aradi** [comment]
LGTM, but should be merged only once  #1511 had been merged to main.

**Comment by bhourahine** [comment]
@thomas-niehaus does this need rebasing on main and squashing?

**Comment by thomas-niehaus** [comment]
No, don't think so.

**Comment by thomas-niehaus** [comment]
See newer PR #1532

**Pull request closed without merging**
