### PR TITLE
Fixed number of elec with fixed/common Fermi

### PR DESCRIPTION
**Pull request by bhourahine**
As nEl was not updated for fixed Fermi energy / common Fermi level across spins.

### CODE REVIEW

**Review by awvwgk — APPROVED** [review]
Looks good to me

**Comment by bhourahine** [comment]
@awvwgk Looks like there will have to be a follow up for transport as well. Should I do this as another PR, or include it here?

**Comment by awvwgk** [comment]
I think this can be added here. Except you think @pecchia should have a look on this one first.

**Comment by bhourahine** [comment]
@awvwgk the changes are in the main code only.

**Pull request merged**
