### PR TITLE
Switch to consistent use of 'this', instead of 'self'

### PR DESCRIPTION
**Pull request by vanderhe**
In the past there was probably no given convention for using 'this' or 'self'. This PR unifies the usage to 'this' (assuming that this is desired).

It may also be advisable to adapt the [DFTB+ Developers Guide](https://dftbplus-develguide.readthedocs.io/en/latest/fortranstyle.html) to establish the convention introduced by the commit below.

### CODE REVIEW

**Comment by bhourahine** [comment]
This might have to stay as in progress for a while as there are several PRs just about to be merged that won't be following this convention so will need fixing.

**Comment by vanderhe** [comment]
Alright, just let me know when there is a less crowded time window in terms of PR's and I will try to resolve any conflicts that have occurred up to that point, ASAP.

**Comment by bhourahine** [comment]
Will do. Approximately a week or two should do it (you should discuss the planned 20.1 release schedule with @aradi since things settle down at that point).

**Comment by bhourahine** [comment]
The pre-release PRs are mostly merged now, so could you resolve the conflicts?

**Comment by vanderhe** [comment]
Conflicts resolved.

**Comment by bhourahine** [comment]
Just waiting on various compilers to complete and then will merge.

Do you want to also make a PR into the devel guide [repo](https://github.com/dftbplus/develguide) to cover the style change?

**Pull request merged**
