### PR TITLE
Migrate pythonapi's setup.cfg to pyproject.toml

### PR DESCRIPTION
**Pull request by vanderhe**
I also reorganized the flat-/src-layout hybrid as a standard src-layout project and renamed the project from 'pythonapi' to 'dftbplus', which should not have any side-effects e.g. for the [dftbplus-python-feedstock](https://github.com/conda-forge/dftbplus-python-feedstock).

In any case, the recipes are outdated (still referring to `setup.py`), so a supplementary PR in [dftbplus/recipes](https://github.com/dftbplus/recipes) is needed.

### CODE REVIEW

**Comment by vanderhe** [comment]
@bhourahine Switched to Python `>=3.10`.

**Review by bhourahine — APPROVED** [review]
LGTM, can you rebase on main (any reason not to also squash the 2 commits together?)

**Comment by vanderhe** [comment]
> LGTM, can you rebase on main (any reason not to also squash the 2 commits together?)

@bhourahine Rebased on main. Strictly spoken the second commit is an unrelated bug fix.

**Comment by bhourahine** [comment]
> @bhourahine Rebased on main. Strictly spoken the second commit is an unrelated bug fix.

@vanderhe it makes sense to keep the commits separate then...

**Pull request merged**
