### PR TITLE
Move modified Gram-Schmidt into math directory

### PR DESCRIPTION
**Pull request by bhourahine**
As this routine is useful outside of linear response routines.

Also fixed some line lengths and comment marks and added a comment to the MPI routines that block column distribution, not block cyclic, is used in the linrespgrad/linrespcommon routines for supervectors.

### CODE REVIEW

**Comment by thomas-niehaus** [comment]
There are a couple of PR waiting and this one is based on main. The refactoring changed all calls to action* so some of your changes are obsolete. 

I fully agree that Gram-Schmidt should be general but maybe we should wait for this PR up to the merging of all other PR.

**Comment by bhourahine** [comment]
@thomas-niehaus @aradi now rebased on main.

**Comment by bhourahine** [comment]
@thomas-niehaus are there any outstanding PRs to merge first?

**Comment by thomas-niehaus** [comment]
Let me work on ATQ first....

**Comment by bhourahine** [comment]
> Let me work on ATQ first....

Sure. One thing I also noticed is that the Stratmann solver doesn't have sutable tests for the GS being broken

**Pull request merged**
