### PR TITLE
Remove unused gbs eigensolver

### PR DESCRIPTION
**Pull request by bhourahine**
Drops the unused banded LAPACK eigensolvers.

### CODE REVIEW

**Comment by vanderhe** [comment]
Was there any feature in the past that made use of the banded eigensolvers? Not relevant for merging this, I'm just curious...

**Comment by bhourahine** [comment]
@vanderhe Not really. There was a really ancient branch that reorganized the atom numbering to make the H&S matrices more band-like, which reduced the memory use substantially for eigenvalues. The problem is that as soon as you need eigenvectors, the full n*n dense matrix is needed to store them and the memory costs explode.

**Comment by bhourahine** [comment]
Just rebased to current main.

**Review by vanderhe — APPROVED** [review]
LGTM

**Pull request merged**
