### PR TITLE
Documentation building action

### PR DESCRIPTION
**Pull request by awvwgk**
[docs](https://github.com/awvwgk/dftbplus/actions)

Use GH actions to build the DFTB+ manual. Overall runtime is about ~three~ one minute~s~ ~(two minutes for the docker container)~.

- [x] build of the manual is done only for changes in the `doc/dftb+/manual` directory
- [x] uploads of the pdf only for this repository and push events
- [x] upload manual for push events on master

To discuss
- ~run doxygen and/or ford to generate the documentation from the source?~ not used anyway...

Related to #378

### CODE REVIEW

**Comment by awvwgk** [comment]
Check the result here: https://github.com/awvwgk/dftbplus/actions/runs/46720402

**Comment by awvwgk** [comment]
I think this is ready for review now.

**Comment by aradi** [comment]
Wow, it seems to be more complex, than I thought. Building a special Docker-container just in order to run a simple LaTeX command is for me a huge task (with a big CO2 footprint :wink: ) for a very minor advantage. So, let's restrict it to the necessary commits only, when changes had been done in `doc/dftb+/manual`. As for the deployment, not sure, whether a PDF-file hidden somewhere in GitHub actions is of really much use for the users... We can have a quick discussion about this at the next meeting....

**Comment by awvwgk** [comment]
Using an Ubuntu image an installing `texlive-full` will require 6 minutes, so pulling in the docker container saves us 4 minutes download and install for a full texlive stack.

I'm using an Ubuntu image now and only `texlive-latex-extra` and `texlive-science` which reduce the cost of this action to 1 minute (see https://github.com/awvwgk/dftbplus/actions/runs/81440651).

**Comment by awvwgk** [comment]
With the current setup the build will be performed for changes in the `doc/dftb+/manual` directory and report failing manual builds in PR. Generally this should happen at least once per PR (in case it is implementing a new feature).

Merging the PR into master will trigger the build again and upload the manual.

**Pull request closed without merging**
