### PR TITLE
Test for inverting no lattice vectors

### PR DESCRIPTION
**Pull request by bhourahine**
Minor bug, shows up with -ffpe-trap=invalid gnu compiler option.

### CODE REVIEW

**Comment by aradi** [comment]
@pecchia Any objections to get rid of `xinvbox` array and the `coordback` and `difback` routines which use it? Those routines are not called from anywhere apparently.

**Comment by pecchia** [comment]
Hi,

xinvbox is defined in lib_poisson/structure.F90 

Actually now that I look at this I realize the poisson part requires some work for instances…

It is used for the internal ewald summation used in poisson. Sooner or later I will try to fix all that as well.

 

Alex

 

 

Da: Bálint Aradi [mailto:notifications@github.com] 
Inviato: lunedì 9 marzo 2020 16:00
A: dftbplus/dftbplus
Cc: Alessandro Pecchia; Mention
Oggetto: Re: [dftbplus/dftbplus] Test for inverting no lattice vectors (#409)

 

@pecchia <https://github.com/pecchia>  Any objections to get rid of xinvbox array and the coordback and difback routines which use it? Those routines are not called from anywhere apparently.

**Comment by aradi** [comment]
@pecchia Yes, at some point the entire Poisson stuff will need a container, indeed. But for the current fix, we could just delete `xinvbox` and the two routines `difback` and `coordback`, as they are not called from anywhere. I usually prefer to remove dead code if possible.

**Comment by bhourahine** [comment]
At least one of these is used elsewhere, as simply removing them gives a  SIGFPE in the eigensolver routines without NEGF.

**Comment by bhourahine** [comment]
Ah, the SIGFPE is a consequence of testing with -ffpe-trap=invalid suggesting there are other bugs to find elsewhere, but its not due to the removal. So have committed with the routines/variables cut out.

**Comment by bhourahine** [comment]
The floating point error seems to be inside the call to dsyevr in the eigensolvers, so somewhere in openblas on my system.

**Pull request merged**
