### PR TITLE
Non-scc time propagation

### PR DESCRIPTION
**Pull request by fbonafe**
Enable propagation of DM for non-SCC simulations.

### CODE REVIEW

**Comment by fbonafe** [comment]
At the moment it produces some trajectory for molecular systems, but fails for periodic boundary conditions, printing some wrong values every forth step. I attach here an input file that leads to such failure. The problem is not the kick, since it persists with field strength equal to zero. The usual suspect is the initialization of the leapfrog, but that should produce a different output every second step, not every fourth. 


 Geometry = GenFormat {
   14  S
  C  H
    1 1    0.4999999999E+01    0.5017189247E+01    0.2843298238E+01
    2 1    0.4999999999E+01    0.6225386817E+01    0.3587819854E+01
    3 1    0.4999999999E+01    0.5017189247E+01    0.1464314913E+01
    4 1    0.4999999999E+01    0.7461030278E+01    0.2871017995E+01
    5 1    0.4999999999E+01    0.8696673739E+01    0.3587819854E+01
    6 1    0.4999999999E+01    0.6225386817E+01    0.7197932969E+00
    7 1    0.4999999999E+01    0.7461030278E+01    0.1436595156E+01
    8 1    0.4999999999E+01    0.9904871308E+01    0.2843298238E+01
    9 1    0.4999999999E+01    0.8696673739E+01    0.7197932969E+00
   10 1    0.4999999999E+01    0.9904871308E+01    0.1464314913E+01
   11 2    0.4999999999E+01    0.4050594187E+01    0.3362175341E+01
   12 2    0.4999999999E+01    0.4050594187E+01    0.9454378102E+00
   13 2    0.4999999999E+01    0.1087146637E+02    0.3362175341E+01
   14 2    0.4999999999E+01    0.1087146637E+02    0.9454378102E+00
    0.0000000000E+00    0.0000000000E+00    0.0000000000E+00
    0.9999999999E+02    0.0000000000E+00    0.0000000000E+00
    0.0000000000E+00    0.1000003848E+03    0.0000000000E+00
    0.0000000000E+00    0.0000000000E+00    0.4307613151E+01
 }

Hamiltonian = DFTB {
   SlaterKosterFiles = Type2FileNames {
       Separator = "-"
       Suffix = ".skf"
   }   
  MaxAngularMomentum {
    C = "p"
    H = "s"
  }
   KPointsAndWeights = SupercellFolding {
     1 0 0
     0 1 0
     0 0 100 
     0.0 0.0 0.5
   }
}

   ElectronDynamics = {
      Steps = 100
      TimeStep [au] = 0.2
      FieldStrength [v/a] = 0.001
      Perturbation = kick {
       PolarizationDirection = "y"
       }
      WriteEnergyAndCharges = yes
      WriteFrequency = 1
  }

**Comment by fbonafe** [comment]
@aradi @bhourahine this PR is now ready for review. I added tests for kick and laser and disabled forces and ion dynamics in non-SCC calculations.

**Comment by bhourahine** [comment]
@fbonafe Is there merit in bringing this back?

**Comment by fbonafe** [comment]
@bhourahine this feature is already included in PR https://github.com/dftbplus/dftbplus/pull/1544 of @charlymedrano7. Please keep this PR closed until the feature is merged and tested, in case we find these discussions useful.

**Pull request closed without merging**
