### PR TITLE
Add tblite to relevant github actions

### PR DESCRIPTION
**Pull request by bhourahine**

### CODE REVIEW

**Comment by bhourahine** [comment]
The integration test for tblite might be coming up as a fail due to needing either an append to CMAKE_MODULE_PATH  or CMAKE_PREFIX_PATH in its CMakeLists.txt
@aradi any ideas?

**Comment by awvwgk** [comment]
This is an issue in the whole stack of tblite's dependencies, they don't play nicely with CMake package files yet. Will fix this at some point and test integrations upstream, but for now this is not working.

**Comment by bhourahine** [comment]
@awvwgk as the ifort case is running the xtb cases, how about including this for the moment?

**Comment by aradi** [comment]
Note, this is the CMake integration test, which fails, not any of the regression tests. The ifort case does not run the integration test, therefore, it does not trigger the error. I can probably have a look at the tb-lite stack, whether it can be fixed easily enough to export the proper targets...

**Comment by awvwgk** [comment]
This will be fixed with #825

**Pull request closed without merging**
